# Generated by Django 4.2 on 2023-05-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_document_content_alter_document_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.AddField(
            model_name='document',
            name='note',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
